### ISSUE TITLE
deprecated port when running with `--testnet`

### ISSUE THREAD

**Issue by sentientwaffle** [interledgerjs/moneyd-xrp#16]
From `moneyd start --testnet`:

```
2018-03-06T18:31:44.246Z connector:app info connector ready (republic attitude). address=test.amundsen.bmp.port-1801-is-deprecated-see-https-github-com-interledger-interledger-wiki-amundsen.Tqf8qJBf0FUVDxrPjXMK8GMiyoZ-Gm9E8sW39tuhDXM
```

**Comment by sharafian** [comment]
@michielbdejong what's the current port that this should use?

**Comment by michielbdejong** [comment]
Amundsen ports are listed on https://github.com/interledger/interledger/wiki/amundsen#18q1

AFAICT, this issue was fixed in https://github.com/interledgerjs/moneyd-xrp/commit/272c0699dbc42300afa0652042452f4d890c4c5c ?

**Comment by michielbdejong** [comment]
@sentientwaffle probably the old config is saved in your  ~/.moneyd.test.json and/or ~/.moneyd/config-test.json (not sure which one is used now?) - you can either edit them manually (changing port 1801 to 1811), or remove them and run configure again, using latest master of moneyd

**Comment by sentientwaffle** [comment]
@michielbdejong you're right -- that commit wasn't published to npm so I was still seeing the warning.

@sharafian bumped the package version, so this is fixed.
